-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_aac_postal`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_aac_postal
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_aac_postal` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique AacPostal ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `postal_code` VARCHAR(10) NOT NULL,
  `aac_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_aac_postal_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
